@host = http://localhost:8080
@user = sample-client
@password = redacted

###

GET {{host}}/actuator/info
# Authorization: Basic {{user}} {{password}}

###

GET {{host}}/actuator/health
# Authorization: Basic {{user}} {{password}}

###

GET {{host}}/actuator/health/liveness
# Authorization: Basic {{user}} {{password}}

###

GET {{host}}/actuator/health/readiness
# Authorization: Basic {{user}} {{password}}

###

POST {{host}}/person HTTP/1.1
Content-Type: application/json
Authorization: Basic {{user}} {{password}}

{
    "firstName": "john",
    "lastName": "doe"
}

###

GET {{host}}/person
Authorization: Basic {{user}} {{password}}

###

GET {{host}}/person/1
Authorization: Basic {{user}} {{password}}

###

POST {{host}}/kube/ignore
Content-Type: application/json
Authorization: Basic {{user}} {{password}}

30

###

GET {{host}}/client/xml

###

GET {{host}}/client/xmlInJson

###

GET {{host}}/client/getXml
Accept: application/xml

###

GET {{host}}/client/getError

###

GET {{host}}/client/getXmlInJson
# Accept: application/json

###

GET {{host}}/client/getXmlFlux
Accept: application/xml

###

GET {{host}}/client/getXmlInJsonFlux
# Accept: application/json

###

GET {{host}}/message/sendNow

###

GET {{host}}/message/getOne

###

GET {{host}}/person/echo?id=456&firstName=John&lastName=Doe

###

POST {{host}}/person/echo
Content-Type: application/json

{
    "id": 123,
    "firstName": "John",
    "lastName": "Doe"
}

###

POST {{host}}/authorize
Authorization: Basic testuser testpass

###

POST {{host}}/document/storeWithMeta
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="meta"

sample-meta
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="README2.md"
Content-Type: text/markdown

< ./README.md
------WebKitFormBoundary7MA4YWxkTrZu0gW--
