@host = http://localhost:8080
@user = {{basicUser}}
@password = {{basicPass}}

###

# @name github
POST https://github.com/login/oauth/authorize HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{github-id}} {{github-secret}}

grant_type=client_credentials&scope=example.scope&client_id=myappid

###

GET {{host}}/authorize
Authorization: Basic {{user}} {{password}}

###

GET {{host}}/authorize
Authorization: Bearer {{github-pat}}

###

GET {{host}}/swagger-ui/index.html

###

GET {{host}}/v3/api-docs

###

GET {{host}}/actuator/info
# Authorization: Basic {{user}} {{password}}

###

GET {{host}}/actuator/health
# Authorization: Basic {{user}} {{password}}

###

GET {{host}}/actuator/health/liveness
# Authorization: Basic {{user}} {{password}}

###

GET {{host}}/actuator/health/readiness
# Authorization: Basic {{user}} {{password}}

###

GET {{host}}/actuator/mappings
# Authorization: Basic {{user}} {{password}}

###

POST {{host}}/person HTTP/1.1
Content-Type: application/json
Authorization: Basic {{user}} {{password}}

{
    "firstName": "john",
    "lastName": "doe"
}

###

GET {{host}}/person
Authorization: Basic {{user}} {{password}}

###

GET {{host}}/person/1
Authorization: Basic {{user}} {{password}}

###

POST {{host}}/kube/ignore
Content-Type: application/json
Authorization: Basic {{user}} {{password}}

30

###

GET {{host}}/data/xml

###

GET {{host}}/data/xmlInJson

###

GET {{host}}/client/getXml
Accept: application/xml

###

GET {{host}}/client/getPerson
Accept: application/xml

###

GET {{host}}/client/getError

###

GET {{host}}/client/getXmlInJson
# Accept: application/json

###

GET {{host}}/client/getXmlFlux
Accept: application/xml

###

GET {{host}}/client/getXmlInJsonFlux
# Accept: application/json

###

GET {{host}}/client/getPersonFlux
Accept: application/xml

###

GET {{host}}/message/publishNow
x-count: 15

###

GET {{host}}/message/sendNow
x-count: 50

###

GET {{host}}/message/sendLater

###

GET {{host}}/message/sendBackoff

###

GET {{host}}/message/getOne

###

GET {{host}}/message/getAll
###

GET {{host}}/message/getAllSubscriptions

###

GET {{host}}/message/count

###

GET {{host}}/message/registry/listeners

###

GET {{host}}/message/registry/start

###

GET {{host}}/message/registry/stop

###

GET {{host}}/person/echo?id=456&firstName=John&lastName=Doe

###

POST {{host}}/person/echo
Content-Type: application/json

{
    "id": 123,
    "firstName": "John",
    "lastName": "Doe"
}

###

GET {{host}}/state/demo
Content-Type: application/json

###

POST {{host}}/authorize
Authorization: Basic testuser testpass

###

GET {{host}}/document?sortBy=createDateTime&sortOrder=desc

###

GET {{host}}/document?size=1&page=2&sortBy=fileName

###

GET {{host}}/document/17311236-2D47-4BD5-BDDC-39E35BCBBD7D

###

POST {{host}}/document/store
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="README2.md"
Content-Type: text/markdown

< ./README.md
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

POST {{host}}/document/store
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="meta"
Content-Type: application/json

{"prop1":"value1"}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="README2.md"
Content-Type: text/markdown

< ./README.md
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

GET {{host}}/document/3af0017d-e60b-4d8d-a27a-e1b609281ba2/binary

###

GET {{host}}/document/3af0017d-e60b-4d8d-a27a-e1b609281ba2/binary?transform=true

###

POST {{host}}/cloud/entity/echo/shell
Content-Type: application/cloudevents+json

{
    "specversion" : "1.0",
    "type" : "com.dapr.cloudevent.sent",
    "source" : "testcloudeventspubsub",
    "subject" : "Cloud Events Test",
    "id" : "someCloudEventId",
    "time" : "2021-08-02T09:00:00Z",
    "datacontenttype" : "application/json",
    "data" : { "orderId": "100" },
    "ce-data" : { "orderId2": "200" },
    "oneMore" : "test",
    "ce-test2" : "anotherprop"
}

###

POST {{host}}/cloud/event/echo/data
Content-Type: application/cloudevents+json

{
    "specversion" : "1.0",
    "type" : "com.dapr.cloudevent.sent",
    "source" : "testcloudeventspubsub",
    "subject" : "Cloud Events Test",
    "id" : "someCloudEventId",
    "time" : "2021-08-02T09:00:00Z",
    "datacontenttype" : "application/cloudevents+json",
    "data" : { "orderId": "100" }
}

###

POST {{host}}/cloud/entity/echo/shell
# Content-Type: application/cloudevents+json
Content-Type: application/json
Ce-time: 2021-07-21T08:00:07.46Z
Ce-specversion: 1.0
Ce-primaryobjectid: rec:5
Ce-primaryobjecttype: Book
Ce-transactionid: f6e64758-ecc0-4f54-9adc-0b0366fbd1a3
Ce-version: 1.1
Ce-primaryeventcount: 28
Ce-source: server:url:
Ce-id: 33dd6cec-6d8c-4e95-bcb6-f59f17b2191c
Ce-type: com.example.Book
Ce-objectid: obj:1
Ce-objecttype: Book
Ce-language: en-US
Ce-subject: 
Ce-worksetid: DEFAULT
Ce-partitionkey: obj:3

{
  "notes": {},
  "description": "Tale of two cities",
  "author": {
    "first": "Charles",
    "last": "Dickens"
  },
  "id": "id:001",
  "deweydecimal": "823.8"
}

###
GET {{host}}/data/sampleJson

###
GET {{host}}/data/parseJson

###
GET {{host}}/data/saveJson

###
GET {{host}}/data/loadJson/D73D2DDA-C1A5-4D48-8523-4BDBA5F7B588

###
GET {{host}}/data/parseJson?useNodeName=false

###
GET {{host}}/data/json2xml
