# @host = http://localhost:30005    # pull from environments in settings.json
@user = {{$dotenv BASIC_USER}}
@admin = {{$dotenv BASIC_ADMIN}}
@password = {{$dotenv BASIC_PASSWORD}}

@github-id = {{$dotenv github-id}}
@github-secret = {{$dotenv github-secret}}

###
# @name github-pat

POST https://github.com/login/oauth/authorize HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{github-id}} {{github-secret}}

grant_type=client_credentials&scope=example.scope&client_id=myappid

###

GET {{host}}/authorize
Authorization: Basic {{user}} {{password}}

###

GET {{host}}/authorize
Authorization: Bearer {{github-pat}}

###
# @name jwtUser

POST {{host}}/token/jwt
Authorization: Basic {{user}} {{password}}

###
# @name jwtUser

POST {{host}}/token/jws
Authorization: Basic {{user}} {{password}}

###
# @name jwtAdmin

POST {{host}}/token/jwt
Authorization: Basic {{admin}} {{password}}

###

GET {{host}}/swagger-ui/index.html

###

GET {{host}}/v3/api-docs

###

GET {{host}}/actuator/info
# Authorization: Bearer {{jwt.response.body.*}}
# Authorization: Basic {{user}} {{password}}

###
GET {{host}}/actuator/env

###

GET {{host}}/actuator/health
# Authorization: Basic {{user}} {{password}}

###

GET {{host}}/actuator/health/liveness
# Authorization: Basic {{user}} {{password}}

###

GET {{host}}/actuator/health/readiness
# Authorization: Basic {{user}} {{password}}

###

GET {{host}}/actuator/scheduledtasks
Authorization: Bearer {{jwtUser.response.body.*}}
# Authorization: Basic {{user}} {{password}}

###

GET {{host}}/actuator/mappings
Authorization: Bearer {{jwtUser.response.body.*}}
# Authorization: Basic {{user}} {{password}}

###

GET {{host}}/actuator/mappings
Authorization: Bearer {{jwtAdmin.response.body.*}}
# Authorization: Basic {{user}} {{password}}

###

POST {{host}}/person HTTP/1.1
Content-Type: application/json
Authorization: Basic {{user}} {{password}}

{
    "firstName": "john",
    "lastName": "doe"
}

###

GET {{host}}/person
Authorization: Bearer {{jwtUser.response.body.*}}
# Authorization: Basic {{user}} {{password}}

###

GET {{host}}/person/1
Authorization: Basic {{user}} {{password}}

###

GET {{host}}/person/add-multiple HTTP/1.1
Content-Type: application/json
Authorization: Basic {{user}} {{password}}

###

POST {{host}}/kube/ignore
Content-Type: application/json
Authorization: Basic {{user}} {{password}}

30

###
GET {{host}}/broadcast/servers/spring-demo-headless

###
GET {{host}}/broadcast/info/spring-demo-headless

###
GET {{host}}/broadcast/proxy/spring-demo-headless/actuator/health/liveness

###
GET {{host}}/broadcast/endpoint/spring-demo-app/actuator/health/liveness

###
GET {{host}}/broadcast/client-endpoint/spring-demo-app/actuator/health/liveness

###

GET {{host}}/data/xml

###

GET {{host}}/data/xmlInJson

###

GET http://localhost:30005/data/loadDates

###

GET {{host}}/data/loadDates

###

GET {{host}}/client/getXml
Accept: application/xml

###

GET {{host}}/client/getPerson
Accept: application/xml

###

GET {{host}}/client/getError

###

GET {{host}}/client/getXmlInJson
# Accept: application/json

###

GET {{host}}/client/getXmlFlux
Accept: application/xml

###

GET {{host}}/client/getXmlInJsonFlux
# Accept: application/json

###

GET {{host}}/client/getPersonFlux
Accept: application/xml

###

GET {{host}}/client/flux/document/binary/9abb4957-c7cf-471c-8684-25e93a4a8dd9
Accept-Encoding: gzip

###

GET {{host}}/client/fluxjdk/document/binary/9abb4957-c7cf-471c-8684-25e93a4a8dd9
Accept-Encoding: gzip
# Accept-Encoding: identity

###

GET {{host}}/message/publishNow
x-count: 15

###

GET {{host}}/message/sendNow
x-count: 1
x-env: poc

###

GET {{host}}/message/messaging/sendNow
x-count: 1
x-env: msg

###

GET {{host}}/message/sendLater

###

GET {{host}}/message/sendBackoff

###

GET {{host}}/message/getOne

###

GET {{host}}/message/getAll
###

GET {{host}}/message/getAllSubscriptions

###

GET {{host}}/message/count

###

GET {{host}}/message/registry/listeners

###

GET {{host}}/message/registry/start

###

GET {{host}}/message/registry/stop

###

GET {{host}}/person/echo?id=456&firstName=John&lastName=Doe

###

POST {{host}}/person/echo
Content-Type: application/json

{
    "id": 123,
    "firstName": "John",
    "lastName": "Doe"
}

###

GET {{host}}/state/demo
Content-Type: application/json

###

GET {{host}}/tasks/schedules

###

GET {{host}}/tasks/schedules/sample/stop

###

GET {{host}}/tasks/schedules/sample/start

###

GET {{host}}/uml/fonts/PNG
###

GET {{host}}/uml/test
###

POST {{host}}/uml/generate/PNG
###

POST {{host}}/uml/class/PNG

###

POST {{host}}/authorize
Authorization: Basic testuser testpass

###

GET {{host}}/document?sortBy=createDateTime&sortOrder=desc&page=0&size=100

###

GET {{host}}/document?size=1&page=2&sortBy=fileName

###

GET {{host}}/document/9abb4957-c7cf-471c-8684-25e93a4a8dd9

###

POST {{host}}/document/store
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="README2.md"
Content-Type: text/markdown

< ./README.md
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

POST {{host}}/document/store
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="meta"
Content-Type: application/json

{"prop1":"value1"}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="README2.md"
Content-Type: text/markdown

< ./README.md
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# GET {{host}}/document/3af0017d-e60b-4d8d-a27a-e1b609281ba2/binary
GET {{host}}/document/9abb4957-c7cf-471c-8684-25e93a4a8dd9/binary

###

GET {{host}}/document/3af0017d-e60b-4d8d-a27a-e1b609281ba2/binary?transform=true

###

POST {{host}}/cloud/entity/echo/shell
Content-Type: application/cloudevents+json

{
    "specversion" : "1.0",
    "type" : "com.dapr.cloudevent.sent",
    "source" : "testcloudeventspubsub",
    "subject" : "Cloud Events Test",
    "id" : "someCloudEventId",
    "time" : "2021-08-02T09:00:00Z",
    "datacontenttype" : "application/json",
    "data" : { "orderId": "100" },
    "ce-data" : { "orderId2": "200" },
    "oneMore" : "test",
    "ce-test2" : "anotherprop"
}

###

POST {{host}}/cloud/event/echo/data
Content-Type: application/cloudevents+json

{
    "specversion" : "1.0",
    "type" : "com.dapr.cloudevent.sent",
    "source" : "testcloudeventspubsub",
    "subject" : "Cloud Events Test",
    "id" : "someCloudEventId",
    "time" : "2021-08-02T09:00:00Z",
    "datacontenttype" : "application/cloudevents+json",
    "data" : { "orderId": "100" }
}

###

POST {{host}}/cloud/entity/echo/shell
# Content-Type: application/cloudevents+json
Content-Type: application/json
Ce-time: 2021-07-21T08:00:07.46Z
Ce-specversion: 1.0
Ce-primaryobjectid: rec:5
Ce-primaryobjecttype: Book
Ce-transactionid: f6e64758-ecc0-4f54-9adc-0b0366fbd1a3
Ce-version: 1.1
Ce-primaryeventcount: 28
Ce-source: server:url:
Ce-id: 33dd6cec-6d8c-4e95-bcb6-f59f17b2191c
Ce-type: com.example.Book
Ce-objectid: obj:1
Ce-objecttype: Book
Ce-language: en-US
Ce-subject: 
Ce-worksetid: DEFAULT
Ce-partitionkey: obj:3

{
  "notes": {},
  "description": "Tale of two cities",
  "author": {
    "first": "Charles",
    "last": "Dickens"
  },
  "id": "id:001",
  "deweydecimal": "823.8"
}

###
GET {{host}}/data/sampleJson

###
GET {{host}}/data/parseJson

###
GET {{host}}/data/saveJson

###
GET {{host}}/data/loadJson/D73D2DDA-C1A5-4D48-8523-4BDBA5F7B588

###
GET {{host}}/data/parseJson?useNodeName=false

###
GET {{host}}/data/json2xml

###
GET {{host}}/deception/runAround

###
POST {{host}}/ws HTTP/1.1
Content-Type: text/xml
SOAPAction: ""

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xop-mime='http://www.w3.org/2005/05/xmlmime'>
   <soapenv:Body>
      <ReadStorageRecordRequest xmlns="https://springdemo.example.com/soap">
         <name>classes/git.properties</name>
      </ReadStorageRecordRequest>
    </soapenv:Body>
</soapenv:Envelope>

###
# mtom encoded data
# "fileName": "spring-tool-suite-4-4.13.0.RELEASE-e4.22.0-macosx.cocoa.aarch64.dmg"
# "fileName": "spring-tool-suite-4-4.13.0.RELEASE-e4.22.0-macosx.cocoa.aarch64.dmg"
# "fileName": "769-26093.pdf"

POST {{host}}/document/record/save
Content-Type: application/json

{
  "contentType": "application/pdf",
  "fileName": "TestDocWithHyperlinks.pdf"
}

###
POST {{host}}/ws HTTP/1.1
Content-Type: multipart/related; start="root@espringdemo"; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW; type="application/xop+xml"; start-info="text/xml"
SOAPAction: ""

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: application/xop+xml; charset=utf-8; type="text/xml"
Content-ID: <root@espringdemo>

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xop-mime='http://www.w3.org/2005/05/xmlmime'>
   <soapenv:Body>
      <SaveStorageRecordRequest xmlns="https://springdemo.example.com/soap">
         <StorageRecord>
            <name>README.md</name>
            <contentType>text/markdown</contentType>
            <content xop-mime:content-type='text/markdown'>
               <Include href="cid:document@example.com" xmlns="http://www.w3.org/2004/08/xop/include"/>
            </content>
         </StorageRecord>
      </SaveStorageRecordRequest>
    </soapenv:Body>
</soapenv:Envelope>

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/markdown
Content-Transfer-Encoding: binary
Content-ID: <document@example.com>

< ./README.md

------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
# binary64 encoded data

POST {{host}}/ws HTTP/1.1
Content-Type: multipart/related; start="root@espringdemo"; type="text/xml"; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: application/soap+xml; charset=UTF-8;
Content-ID: <root@espringdemo>

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xop-mime='http://www.w3.org/2005/05/xmlmime'>
   <soapenv:Body>
      <SaveStorageRecordRequest xmlns="https://springdemo.example.com/soap">
         <StorageRecord>
            <name>test.txt</name>
            <contentType>text/plain</contentType>
            <content xop-mime:content-type='text/plain' xop-mime:filename='test.txt'>dGVzdA==</content>
         </StorageRecord>
      </SaveStorageRecordRequest>
    </soapenv:Body>
</soapenv:Envelope>

------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
#
# QUEUE
#

GET {{host}}/queue/addMany?items=5000

###

GET {{host}}/queue/manyNext?threads=15

###

GET {{host}}/queue/manyPrefetch?threads=15&prefetch=50

###

GET {{host}}/queue/resetErrors

###
#
# ORDERED
#

GET {{host}}/queue/order/addMany?items=5000&order=150

###

GET {{host}}/queue/order/next

###

GET {{host}}/queue/order/manyNext?threads=15

###

GET {{host}}/queue/order/manyPrefetch?threads=15&prefetch=50

###

GET {{host}}/queue/order/resetErrors
