apiVersion: v1
kind: Namespace
metadata:
  name: spring-demo
  labels:
    name: spring-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo-app
  labels:
    app: spring-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-demo-app
  template:
    metadata:
      labels:
        app: spring-demo-app
    spec:
      containers:
      - name: spring-demo-app
        image: spring-demo:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: spring-demo-app
  labels:
    name: spring-demo-app
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
  selector:
    app: spring-demo-app
