
apiVersion: v1
kind: Namespace
metadata:
  name: spring-demo
  labels:
    name: spring-demo

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: spring-demo
  name: namespace-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: spring-demo
  name: namespace-leader
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "update"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding
  namespace: spring-demo
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-leader-binding
  namespace: spring-demo
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
roleRef:
  kind: Role
  name: namespace-leader
  apiGroup: ""

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-demo
  namespace: spring-demo
data:
  info.kube.prop: Sourced from ConfigMap
  info.kube.prop2: another prop from ConfigMap
  # application-kubernetes.properties: |-
  #   info.kube.prop=Sourced from ConfigMap

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-demo-leader
  namespace: spring-demo

---

apiVersion: v1
kind: Secret
metadata:
  name: datasource
  namespace: spring-demo
type: Opaque
data:
  password: UGFzc3cwcmQh

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo-app
  labels:
    app: spring-demo-app
  namespace: spring-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-demo-app
  template:
    metadata:
      labels:
        app: spring-demo-app
    spec:
      containers:
      - name: spring-demo-app
        image: spring-demo:0.0.1
        env:
        - name: BPL_JAVA_NMT_ENABLED
          value: "false"
        - name: SPRING_PROFILES_ACTIVE
          value: "mssql,local"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:sqlserver://sqledge;trustServerCertificate=true"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: datasource
              key: password
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi

---

apiVersion: v1
kind: Service
metadata:
  name: spring-demo-app
  labels:
    name: spring-demo-app
  namespace: spring-demo
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
      nodePort: 30005
  selector:
    app: spring-demo-app
