spring:
    datasource:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        # url: jdbc:sqlserver://localhost;databaseName=model
        url: jdbc:sqlserver://localhost;trustServerCertificate=true
        username: sa
        maximum-pool-size: ${spring.datasource.pool-size}
        # password: redacted
    sql:
        init:
            platform: mssql
    #         schema-locations: classpath:schema-mssql.sql
    liquibase:
        parameters:
            "liquibase.liquibaseSchemaName": dbo