management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: "*"

spring:
#     sql:
#         init:
#             mode: always
    output:
        ansi:
            enabled: ALWAYS