spring:
    application:
        name: spring-demo
    lifecycle:
        timeout-per-shutdown-phase: 20s
    # datasource: 
        # driver-class-name: com.mysql.jdbc.Driver
        # url: jdbc:mysql://localhost/test
        # username: dbuser
        # password: dbpass

management:
    cloudfoundry:
        enabled: false
    security:
        enabled: false
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: "*"
            #     - health
            #     - metrics
            #     - env
            #     - info
            # cors:
            #     allowed-origins: http://example.com
            #     allowed-methods: GET,POST
    endpoint:
        info:
            enabled: true
        metrics:
            enabled: true
        env:
            enabled: true
        health:
            enabled: true
            show-details: always
            show-components: always
            probes:
                enabled: true
    health:
        livenessState:
            enabled: true
        readinessState:
            enabled: true

server:
    shutdown: graceful
    compression:
        enabled: true
    http2:
        enabled: true
    port: 8080
