spring:
    datasource:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        # url: jdbc:sqlserver://localhost;databaseName=model
        url: jdbc:sqlserver://localhost
        username: sa
        maximum-pool-size: ${sample.datasource.maximum-pool-size}
        # password: redacted
    sql:
        init:
            platform: mssql
    #         schema-locations: classpath:schema-mssql.sql