spring:
    application:
        name: spring-demo
        admin:
            enabled: false
    lifecycle:
        timeout-per-shutdown-phase: 20s
    sql:
        init:
            mode: embedded
    jmx:
        enabled: false
    main:
        banner-mode: console
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:props
        username: sa
        # jdbc-url is needed for Hikari
        jdbc-url: ${spring.datasource.url}
        pool-size: 30
        maximum-pool-size: 30
        hikari:
            maximum-pool-size: 30
            auto-commit: true
    profiles:
        default: custom

logging:
  level:
    root: info
    "[org.springframework]": info
    
management:
    cloudfoundry:
        enabled: false
    security:
        enabled: false
    endpoints:
        enabled-by-default: false
        web:
            exposure:
                # include: 
                include:
                - health
                - info
            # cors:
            #     allowed-origins: http://example.com
            #     allowed-methods: GET,POST
    endpoint:
        info:
            enabled: true
        health:
            enabled: true
            show-details: always
            show-components: always
            probes:
                enabled: true
    health:
        livenessState:
            enabled: true
        readinessState:
            enabled: true

server:
    shutdown: graceful
    compression:
        enabled: true
    http2:
        enabled: true
    port: 8080
    session-timeout: 1800
    max-threads: 50

sample:
    commandLine:
        delay: 5
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:custom
        username: sa
        # jdbc-url is needed for Hikari
        jdbc-url: ${sample.datasource.url}
        maximum-pool-size: 30
    hikari:
        datasource:
            driver-class-name: org.h2.Driver
            url: jdbc:h2:mem:hikari
            username: sa
            # jdbc-url is needed for Hikari
            jdbc-url: ${sample.hikari.datasource.url}
            maximum-pool-size: 30
    