CREATE TABLE IF NOT EXISTS PERSON(
    ID IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS APP_EVENT(
    ID varchar(36) PRIMARY KEY,
    CREATE_DT datetime,
    EVENT_BODY varchar(max),
    EVENT_BIN BLOB
);

CREATE TABLE IF NOT EXISTS DOCUMENT(
    ID varchar(36) PRIMARY KEY,
    CONTENT_TYPE varchar(255),
    CONTENT_LEN int,
    FILE_NM varchar(255),
    DOC_BIN BLOB,
    CREATE_DT datetime,
    CHECKSUM varchar(40)
);