apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqledge
  namespace: spring-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqledge
  template:
    metadata:
      labels:
        app: sqledge
    spec:
      # volumes:
      #   - name: sqldata
      #     persistentVolumeClaim:
      #       claimName: mssql-data
      containers:
        - name: azuresqledge
          image: mcr.microsoft.com/azure-sql-edge:latest
          ports:
            - containerPort: 1433
          imagePullPolicy: IfNotPresent
          # volumeMounts:
          #   - name: sqldata
          #     mountPath: /var/opt/mssql
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datasource
                  key: password
            - name: MSSQL_AGENT_ENABLED
              value: "TRUE"
            - name: MSSQL_COLLATION
              value: "SQL_Latin1_General_CP1_CI_AS"
            - name: MSSQL_LCID
              value: "1033"
            - name: TZ
              value: "America/New_York"
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
          # securityContext:
          #   capabilities:
          #     add:
          #       - SYS_PTRACE
          # lifecycle:
          #   postStart:
          #     exec:
          #       command: ["/bin/sh", "-c", ]
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 10001

---

apiVersion: v1
kind: Service
metadata:
  name: sqledge
  namespace: spring-demo
spec:
  selector:
    app: sqledge
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      name: sql
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: sqledge-node
  namespace: spring-demo
spec:
  selector:
    app: sqledge
  ports:
    - protocol: TCP
      port: 1433
      name: sql
      nodePort: 31433
  type: NodePort