
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-demo
  namespace: spring-demo
data:
  info.kube.prop: Sourced from ConfigMap
  info.kube.prop2: another prop from ConfigMap
  # application-kubernetes.properties: |-
  #   info.kube.prop=Sourced from ConfigMap

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-demo-leader
  namespace: spring-demo

---

apiVersion: v1
kind: Secret
metadata:
  name: datasource
  namespace: spring-demo
type: Opaque
data:
  password: UGFzc3cwcmQh
