driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
url=jdbc:sqlserver://localhost:31433;databaseName=SpringDemo;trustServerCertificate=true
changeLogFile=/liquibase/master.xml
liquibase.convertDataTypes=false
#liquibaseSchemaName=dbo
#liquibase.liquibaseSchemaName=dbo
#changeExecListenerClass=com.example.springdemo.util.LBChangeExecListener

#liquibase-schema-name=dbo
#liquibase.command.defaultSchemaName=dbo

#parameter.schema-name=${liquibaseSchemaName}
#parameter.schema-name=${liquibase-schema-name}
parameter.schema-name=dbo
